apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-amqstreams-operator

bases:
  - ../stable

resources:
  - openshift-amqstreams-operator-namespace.yaml
  - operator-group.yaml
